default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: brettpuddick_development
test:
  <<: *default
  database: brettpuddick_test
production:
  <<: *default
  database: brettpuddick_production
  username: brettpuddick
  password: <%= ENV["DATABASE_PASSWORD"] %>
